/** Catalog from languages.csv. Corpus files are in wikipedia_dicts/. */
export const LANGUAGES = [
  {"code": "ab", "name": "аԥсшәа", "english": "Abkhaz", "path": "wikipedia_dicts/ab.csv"},
  {"code": "ace", "name": "Acèh", "english": "Acehnese", "path": "wikipedia_dicts/ace.csv"},
  {"code": "ady", "name": "адыгабзэ", "english": "Adyghe", "path": "wikipedia_dicts/ady.csv"},
  {"code": "af", "name": "Afrikaans", "english": "Afrikaans", "path": "wikipedia_dicts/af.csv"},
  {"code": "alt", "name": "алтай тил", "english": "Southern Altai", "path": "wikipedia_dicts/alt.csv"},
  {"code": "am", "name": "አማርኛ", "english": "Amharic", "path": "wikipedia_dicts/am.csv"},
  {"code": "ami", "name": "Pangcah", "english": "Amis", "path": "wikipedia_dicts/ami.csv"},
  {"code": "an", "name": "aragonés", "english": "Aragonese", "path": "wikipedia_dicts/an.csv"},
  {"code": "ang", "name": "Ænglisc", "english": "Old English", "path": "wikipedia_dicts/ang.csv"},
  {"code": "arc", "name": "ܐܪܡܝܐ", "english": "Aramaic", "path": "wikipedia_dicts/arc.csv"},
  {"code": "ast", "name": "asturianu", "english": "Asturian", "path": "wikipedia_dicts/ast.csv"},
  {"code": "atj", "name": "Atikamekw", "english": "Atikamekw", "path": "wikipedia_dicts/atj.csv"},
  {"code": "av", "name": "авар", "english": "Avar", "path": "wikipedia_dicts/av.csv"},
  {"code": "avk", "name": "Kotava", "english": "Kotava", "path": "wikipedia_dicts/avk.csv"},
  {"code": "ay", "name": "Aymar aru", "english": "Aymara", "path": "wikipedia_dicts/ay.csv"},
  {"code": "az", "name": "azərbaycanca", "english": "Azerbaijani", "path": "wikipedia_dicts/az.csv"},
  {"code": "ba", "name": "башҡортса", "english": "Bashkir", "path": "wikipedia_dicts/ba.csv"},
  {"code": "ban", "name": "Basa Bali", "english": "Balinese", "path": "wikipedia_dicts/ban.csv"},
  {"code": "bar", "name": "Boarisch", "english": "Bavarian", "path": "wikipedia_dicts/bar.csv"},
  {"code": "bcl", "name": "Bikol Central", "english": "Central Bikol", "path": "wikipedia_dicts/bcl.csv"},
  {"code": "be", "name": "беларуская", "english": "Belarusian", "path": "wikipedia_dicts/be.csv"},
  {"code": "bg", "name": "български", "english": "Bulgarian", "path": "wikipedia_dicts/bg.csv"},
  {"code": "bi", "name": "Bislama", "english": "Bislama", "path": "wikipedia_dicts/bi.csv"},
  {"code": "bjn", "name": "Banjar", "english": "Banjar", "path": "wikipedia_dicts/bjn.csv"},
  {"code": "bm", "name": "bamanankan", "english": "Bambara", "path": "wikipedia_dicts/bm.csv"},
  {"code": "br", "name": "brezhoneg", "english": "Breton", "path": "wikipedia_dicts/br.csv"},
  {"code": "bs", "name": "bosanski", "english": "Bosnian", "path": "wikipedia_dicts/bs.csv"},
  {"code": "bug", "name": "Basa Ugi", "english": "Buginese", "path": "wikipedia_dicts/bug.csv"},
  {"code": "bxr", "name": "буряад", "english": "Russia Buriat", "path": "wikipedia_dicts/bxr.csv"},
  {"code": "ca", "name": "català", "english": "Catalan", "path": "wikipedia_dicts/ca.csv"},
  {"code": "cbk", "name": "Chavacano de Zamboanga", "english": "Zamboanga Chavacano", "path": "wikipedia_dicts/cbk-zam.csv"},
  {"code": "cdo", "name": "Mìng-dĕ̤ng-ngṳ̄", "english": "Min Dong", "path": "wikipedia_dicts/cdo.csv"},
  {"code": "ce", "name": "нохчийн", "english": "Chechen", "path": "wikipedia_dicts/ce.csv"},
  {"code": "ceb", "name": "Cebuano", "english": "Cebuano", "path": "wikipedia_dicts/ceb.csv"},
  {"code": "ch", "name": "Chamoru", "english": "Chamorro", "path": "wikipedia_dicts/ch.csv"},
  {"code": "chr", "name": "ᏣᎳᎩ", "english": "Cherokee", "path": "wikipedia_dicts/chr.csv"},
  {"code": "chy", "name": "Tsetsêhestâhese", "english": "Cheyenne", "path": "wikipedia_dicts/chy.csv"},
  {"code": "co", "name": "corsu", "english": "Corsican", "path": "wikipedia_dicts/co.csv"},
  {"code": "crh", "name": "qırımtatarca", "english": "Crimean Tatar", "path": "wikipedia_dicts/crh.csv"},
  {"code": "cs", "name": "čeština", "english": "Czech", "path": "wikipedia_dicts/cs.csv"},
  {"code": "csb", "name": "kaszëbsczi", "english": "Kashubian", "path": "wikipedia_dicts/csb.csv"},
  {"code": "cu", "name": "словѣньскъ", "english": "Church Slavonic", "path": "wikipedia_dicts/cu.csv"},
  {"code": "cv", "name": "чӑвашла", "english": "Chuvash", "path": "wikipedia_dicts/cv.csv"},
  {"code": "cy", "name": "Cymraeg", "english": "Welsh", "path": "wikipedia_dicts/cy.csv"},
  {"code": "da", "name": "dansk", "english": "Danish", "path": "wikipedia_dicts/da.csv"},
  {"code": "dag", "name": "dagbanli", "english": "Dagbani", "path": "wikipedia_dicts/dag.csv"},
  {"code": "de", "name": "Deutsch", "english": "German", "path": "wikipedia_dicts/de.csv"},
  {"code": "din", "name": "Thuɔŋjäŋ", "english": "Dinka", "path": "wikipedia_dicts/din.csv"},
  {"code": "diq", "name": "Zazaki", "english": "Zazaki", "path": "wikipedia_dicts/diq.csv"},
  {"code": "dsb", "name": "dolnoserbski", "english": "Lower Sorbian", "path": "wikipedia_dicts/dsb.csv"},
  {"code": "dv", "name": "ދިވެހިބަސް", "english": "Dhivehi", "path": "wikipedia_dicts/dv.csv"},
  {"code": "dz", "name": "ཇོང་ཁ", "english": "Dzongkha", "path": "wikipedia_dicts/dz.csv"},
  {"code": "ee", "name": "eʋegbe", "english": "Ewe", "path": "wikipedia_dicts/ee.csv"},
  {"code": "el", "name": "Ελληνικά", "english": "Greek", "path": "wikipedia_dicts/el.csv"},
  {"code": "en", "name": "English", "english": "English", "path": "wikipedia_dicts/en.csv"},
  {"code": "eo", "name": "Esperanto", "english": "Esperanto", "path": "wikipedia_dicts/eo.csv"},
  {"code": "es", "name": "español", "english": "Spanish", "path": "wikipedia_dicts/es.csv"},
  {"code": "et", "name": "eesti", "english": "Estonian", "path": "wikipedia_dicts/et.csv"},
  {"code": "eu", "name": "euskara", "english": "Basque", "path": "wikipedia_dicts/eu.csv"},
  {"code": "ext", "name": "estremeñu", "english": "Extremaduran", "path": "wikipedia_dicts/ext.csv"},
  {"code": "fat", "name": "mfantse", "english": "Fante", "path": "wikipedia_dicts/fat.csv"},
  {"code": "ff", "name": "Fulfulde", "english": "Fula", "path": "wikipedia_dicts/ff.csv"},
  {"code": "fi", "name": "suomi", "english": "Finnish", "path": "wikipedia_dicts/fi.csv"},
  {"code": "fj", "name": "Na Vosa Vakaviti", "english": "Fijian", "path": "wikipedia_dicts/fj.csv"},
  {"code": "fo", "name": "føroyskt", "english": "Faroese", "path": "wikipedia_dicts/fo.csv"},
  {"code": "fon", "name": "fɔ̀ngbè", "english": "Fon", "path": "wikipedia_dicts/fon.csv"},
  {"code": "fr", "name": "français", "english": "French", "path": "wikipedia_dicts/fr.csv"},
  {"code": "frp", "name": "arpetan", "english": "Arpitan", "path": "wikipedia_dicts/frp.csv"},
  {"code": "frr", "name": "Nordfriisk", "english": "Northern Frisian", "path": "wikipedia_dicts/frr.csv"},
  {"code": "fur", "name": "furlan", "english": "Friulian", "path": "wikipedia_dicts/fur.csv"},
  {"code": "fy", "name": "Frysk", "english": "Western Frisian", "path": "wikipedia_dicts/fy.csv"},
  {"code": "ga", "name": "Gaeilge", "english": "Irish", "path": "wikipedia_dicts/ga.csv"},
  {"code": "gag", "name": "Gagauz", "english": "Gagauz", "path": "wikipedia_dicts/gag.csv"},
  {"code": "gcr", "name": "kriyòl gwiyannen", "english": "Guianan Creole", "path": "wikipedia_dicts/gcr.csv"},
  {"code": "gd", "name": "Gàidhlig", "english": "Scottish Gaelic", "path": "wikipedia_dicts/gd.csv"},
  {"code": "gl", "name": "galego", "english": "Galician", "path": "wikipedia_dicts/gl.csv"},
  {"code": "gn", "name": "Avañe'ẽ", "english": "Guarani", "path": "wikipedia_dicts/gn.csv"},
  {"code": "gor", "name": "Bahasa Hulontalo", "english": "Gorontalo", "path": "wikipedia_dicts/gor.csv"},
  {"code": "got", "name": "𐌲𐌿𐍄𐌹𐍃𐌺", "english": "Gothic", "path": "wikipedia_dicts/got.csv"},
  {"code": "gpe", "name": "Ghanaian Pidgin", "english": "Ghanaian Pidgin", "path": "wikipedia_dicts/gpe.csv"},
  {"code": "guc", "name": "wayuunaiki", "english": "Wayuu", "path": "wikipedia_dicts/guc.csv"},
  {"code": "gur", "name": "farefare", "english": "Farefare", "path": "wikipedia_dicts/gur.csv"},
  {"code": "guw", "name": "gungbe", "english": "Gun", "path": "wikipedia_dicts/guw.csv"},
  {"code": "gv", "name": "Gaelg", "english": "Manx", "path": "wikipedia_dicts/gv.csv"},
  {"code": "ha", "name": "Hausa", "english": "Hausa", "path": "wikipedia_dicts/ha.csv"},
  {"code": "hak", "name": "Hak-kâ-ngî", "english": "Hakka", "path": "wikipedia_dicts/hak.csv"},
  {"code": "haw", "name": "Hawaiʻi", "english": "Hawaiian", "path": "wikipedia_dicts/haw.csv"},
  {"code": "hif", "name": "Fiji Hindi", "english": "Fiji Hindi", "path": "wikipedia_dicts/hif.csv"},
  {"code": "hr", "name": "hrvatski", "english": "Croatian", "path": "wikipedia_dicts/hr.csv"},
  {"code": "hsb", "name": "hornjoserbsce", "english": "Upper Sorbian", "path": "wikipedia_dicts/hsb.csv"},
  {"code": "ht", "name": "Kreyòl ayisyen", "english": "Haitian Creole", "path": "wikipedia_dicts/ht.csv"},
  {"code": "hu", "name": "magyar", "english": "Hungarian", "path": "wikipedia_dicts/hu.csv"},
  {"code": "hy", "name": "հայերեն", "english": "Armenian", "path": "wikipedia_dicts/hy.csv"},
  {"code": "hyw", "name": "Արեւմտահայերէն", "english": "Western Armenian", "path": "wikipedia_dicts/hyw.csv"},
  {"code": "ia", "name": "interlingua", "english": "Interlingua", "path": "wikipedia_dicts/ia.csv"},
  {"code": "id", "name": "Bahasa Indonesia", "english": "Indonesian", "path": "wikipedia_dicts/id.csv"},
  {"code": "ie", "name": "Interlingue", "english": "Interlingue", "path": "wikipedia_dicts/ie.csv"},
  {"code": "ig", "name": "Igbo", "english": "Igbo", "path": "wikipedia_dicts/ig.csv"},
  {"code": "ik", "name": "Iñupiatun", "english": "Inupiaq", "path": "wikipedia_dicts/ik.csv"},
  {"code": "ilo", "name": "Ilokano", "english": "Iloko", "path": "wikipedia_dicts/ilo.csv"},
  {"code": "inh", "name": "гӀалгӀай", "english": "Ingush", "path": "wikipedia_dicts/inh.csv"},
  {"code": "io", "name": "Ido", "english": "Ido", "path": "wikipedia_dicts/io.csv"},
  {"code": "is", "name": "íslenska", "english": "Icelandic", "path": "wikipedia_dicts/is.csv"},
  {"code": "it", "name": "italiano", "english": "Italian", "path": "wikipedia_dicts/it.csv"},
  {"code": "jam", "name": "Patois", "english": "Jamaican Creole", "path": "wikipedia_dicts/jam.csv"},
  {"code": "jbo", "name": "la .lojban.", "english": "Lojban", "path": "wikipedia_dicts/jbo.csv"},
  {"code": "jv", "name": "Jawa", "english": "Javanese", "path": "wikipedia_dicts/jv.csv"},
  {"code": "ka", "name": "ქართული", "english": "Georgian", "path": "wikipedia_dicts/ka.csv"},
  {"code": "kaa", "name": "Qaraqalpaqsha", "english": "Kara-Kalpak", "path": "wikipedia_dicts/kaa.csv"},
  {"code": "kab", "name": "Taqbaylit", "english": "Kabyle", "path": "wikipedia_dicts/kab.csv"},
  {"code": "kbd", "name": "адыгэбзэ", "english": "Kabardian", "path": "wikipedia_dicts/kbd.csv"},
  {"code": "kbp", "name": "Kabɩyɛ", "english": "Kabiye", "path": "wikipedia_dicts/kbp.csv"},
  {"code": "kcg", "name": "Tyap", "english": "Tyap", "path": "wikipedia_dicts/kcg.csv"},
  {"code": "ki", "name": "Gĩkũyũ", "english": "Kikuyu", "path": "wikipedia_dicts/ki.csv"},
  {"code": "kl", "name": "kalaallisut", "english": "Kalaallisut", "path": "wikipedia_dicts/kl.csv"},
  {"code": "km", "name": "ភាសាខ្មែរ", "english": "Khmer", "path": "wikipedia_dicts/km.csv"},
  {"code": "kn", "name": "ಕನ್ನಡ", "english": "Kannada", "path": "wikipedia_dicts/kn.csv"},
  {"code": "koi", "name": "перем коми", "english": "Komi-Permyak", "path": "wikipedia_dicts/koi.csv"},
  {"code": "krc", "name": "къарачай-малкъар", "english": "Karachay-Balkar", "path": "wikipedia_dicts/krc.csv"},
  {"code": "ksh", "name": "Ripoarisch", "english": "Colognian", "path": "wikipedia_dicts/ksh.csv"},
  {"code": "ku", "name": "kurdî", "english": "Kurdish", "path": "wikipedia_dicts/ku.csv"},
  {"code": "kv", "name": "коми", "english": "Komi", "path": "wikipedia_dicts/kv.csv"},
  {"code": "kw", "name": "kernowek", "english": "Cornish", "path": "wikipedia_dicts/kw.csv"},
  {"code": "ky", "name": "кыргызча", "english": "Kyrgyz", "path": "wikipedia_dicts/ky.csv"},
  {"code": "la", "name": "Latina", "english": "Latin", "path": "wikipedia_dicts/la.csv"},
  {"code": "lad", "name": "Ladino", "english": "Ladino", "path": "wikipedia_dicts/lad.csv"},
  {"code": "lb", "name": "Lëtzebuergesch", "english": "Luxembourgish", "path": "wikipedia_dicts/lb.csv"},
  {"code": "lbe", "name": "лакку", "english": "Lak", "path": "wikipedia_dicts/lbe.csv"},
  {"code": "lez", "name": "лезги", "english": "Lezghian", "path": "wikipedia_dicts/lez.csv"},
  {"code": "lfn", "name": "Lingua Franca Nova", "english": "Lingua Franca Nova", "path": "wikipedia_dicts/lfn.csv"},
  {"code": "lg", "name": "Luganda", "english": "Ganda", "path": "wikipedia_dicts/lg.csv"},
  {"code": "li", "name": "Limburgs", "english": "Limburgish", "path": "wikipedia_dicts/li.csv"},
  {"code": "lij", "name": "Ligure", "english": "Ligurian", "path": "wikipedia_dicts/lij.csv"},
  {"code": "lld", "name": "Ladin", "english": "Ladin", "path": "wikipedia_dicts/lld.csv"},
  {"code": "lmo", "name": "lombard", "english": "Lombard", "path": "wikipedia_dicts/lmo.csv"},
  {"code": "ln", "name": "lingála", "english": "Lingala", "path": "wikipedia_dicts/ln.csv"},
  {"code": "lt", "name": "lietuvių", "english": "Lithuanian", "path": "wikipedia_dicts/lt.csv"},
  {"code": "ltg", "name": "latgaļu", "english": "Latgalian", "path": "wikipedia_dicts/ltg.csv"},
  {"code": "lv", "name": "latviešu", "english": "Latvian", "path": "wikipedia_dicts/lv.csv"},
  {"code": "mad", "name": "Madhurâ", "english": "Madurese", "path": "wikipedia_dicts/mad.csv"},
  {"code": "mdf", "name": "мокшень", "english": "Moksha", "path": "wikipedia_dicts/mdf.csv"},
  {"code": "mg", "name": "Malagasy", "english": "Malagasy", "path": "wikipedia_dicts/mg.csv"},
  {"code": "mhr", "name": "олык марий", "english": "Eastern Mari", "path": "wikipedia_dicts/mhr.csv"},
  {"code": "mi", "name": "Māori", "english": "Maori", "path": "wikipedia_dicts/mi.csv"},
  {"code": "min", "name": "Minangkabau", "english": "Minangkabau", "path": "wikipedia_dicts/min.csv"},
  {"code": "mk", "name": "македонски", "english": "Macedonian", "path": "wikipedia_dicts/mk.csv"},
  {"code": "mni", "name": "ꯃꯤꯇꯩ ꯂꯣꯟ", "english": "Manipuri", "path": "wikipedia_dicts/mni.csv"},
  {"code": "mrj", "name": "кырык мары", "english": "Western Mari", "path": "wikipedia_dicts/mrj.csv"},
  {"code": "ms", "name": "Bahasa Melayu", "english": "Malay", "path": "wikipedia_dicts/ms.csv"},
  {"code": "mt", "name": "Malti", "english": "Maltese", "path": "wikipedia_dicts/mt.csv"},
  {"code": "mwl", "name": "Mirandés", "english": "Mirandese", "path": "wikipedia_dicts/mwl.csv"},
  {"code": "myv", "name": "эрзянь", "english": "Erzya", "path": "wikipedia_dicts/myv.csv"},
  {"code": "nan", "name": "Bân-lâm-gú", "english": "Min Nan", "path": "wikipedia_dicts/zh-min-nan.csv"},
  {"code": "nap", "name": "Napulitano", "english": "Neapolitan", "path": "wikipedia_dicts/nap.csv"},
  {"code": "nb", "name": "norsk bokmål", "english": "Norwegian Bokmål", "path": "wikipedia_dicts/no.csv"},
  {"code": "nds", "name": "Plattdüütsch", "english": "Low German", "path": "wikipedia_dicts/nds.csv"},
  {"code": "nia", "name": "Li Niha", "english": "Nias", "path": "wikipedia_dicts/nia.csv"},
  {"code": "nl", "name": "Nederlands", "english": "Dutch", "path": "wikipedia_dicts/nl.csv"},
  {"code": "nn", "name": "norsk nynorsk", "english": "Norwegian Nynorsk", "path": "wikipedia_dicts/nn.csv"},
  {"code": "nov", "name": "Novial", "english": "Novial", "path": "wikipedia_dicts/nov.csv"},
  {"code": "nso", "name": "Sesotho sa Leboa", "english": "Northern Sotho", "path": "wikipedia_dicts/nso.csv"},
  {"code": "nv", "name": "Diné bizaad", "english": "Navajo", "path": "wikipedia_dicts/nv.csv"},
  {"code": "ny", "name": "Chi-Chewa", "english": "Chichewa", "path": "wikipedia_dicts/ny.csv"},
  {"code": "oc", "name": "occitan", "english": "Occitan", "path": "wikipedia_dicts/oc.csv"},
  {"code": "olo", "name": "livvinkarjala", "english": "Livvi-Karelian", "path": "wikipedia_dicts/olo.csv"},
  {"code": "om", "name": "Oromoo", "english": "Oromo", "path": "wikipedia_dicts/om.csv"},
  {"code": "or", "name": "ଓଡ଼ିଆ", "english": "Odia", "path": "wikipedia_dicts/or.csv"},
  {"code": "os", "name": "ирон", "english": "Ossetic", "path": "wikipedia_dicts/os.csv"},
  {"code": "pa", "name": "ਪੰਜਾਬੀ", "english": "Punjabi", "path": "wikipedia_dicts/pa.csv"},
  {"code": "pag", "name": "Pangasinan", "english": "Pangasinan", "path": "wikipedia_dicts/pag.csv"},
  {"code": "pam", "name": "Kapampangan", "english": "Pampanga", "path": "wikipedia_dicts/pam.csv"},
  {"code": "pap", "name": "Papiamentu", "english": "Papiamento", "path": "wikipedia_dicts/pap.csv"},
  {"code": "pcd", "name": "Picard", "english": "Picard", "path": "wikipedia_dicts/pcd.csv"},
  {"code": "pcm", "name": "Naijá", "english": "Nigerian Pidgin", "path": "wikipedia_dicts/pcm.csv"},
  {"code": "pdc", "name": "Deitsch", "english": "Pennsylvania German", "path": "wikipedia_dicts/pdc.csv"},
  {"code": "pfl", "name": "Pälzisch", "english": "Palatine German", "path": "wikipedia_dicts/pfl.csv"},
  {"code": "pih", "name": "Norfuk", "english": "Pitcairn-Norfolk", "path": "wikipedia_dicts/pih.csv"},
  {"code": "pl", "name": "polski", "english": "Polish", "path": "wikipedia_dicts/pl.csv"},
  {"code": "pms", "name": "Piemontèis", "english": "Piedmontese", "path": "wikipedia_dicts/pms.csv"},
  {"code": "pnt", "name": "Ποντιακά", "english": "Pontic", "path": "wikipedia_dicts/pnt.csv"},
  {"code": "pt", "name": "português", "english": "Portuguese", "path": "wikipedia_dicts/pt.csv"},
  {"code": "pwn", "name": "pinayuanan", "english": "Paiwan", "path": "wikipedia_dicts/pwn.csv"},
  {"code": "qu", "name": "Runa Simi", "english": "Quechua", "path": "wikipedia_dicts/qu.csv"},
  {"code": "rm", "name": "rumantsch", "english": "Romansh", "path": "wikipedia_dicts/rm.csv"},
  {"code": "rmy", "name": "romani čhib", "english": "Vlax Romani", "path": "wikipedia_dicts/rmy.csv"},
  {"code": "rn", "name": "ikirundi", "english": "Rundi", "path": "wikipedia_dicts/rn.csv"},
  {"code": "ro", "name": "română", "english": "Romanian", "path": "wikipedia_dicts/ro.csv"},
  {"code": "ru", "name": "русский", "english": "Russian", "path": "wikipedia_dicts/ru.csv"},
  {"code": "rue", "name": "русиньскый", "english": "Rusyn", "path": "wikipedia_dicts/rue.csv"},
  {"code": "rup", "name": "armãneashti", "english": "Aromanian", "path": "wikipedia_dicts/roa-rup.csv"},
  {"code": "rw", "name": "Ikinyarwanda", "english": "Kinyarwanda", "path": "wikipedia_dicts/rw.csv"},
  {"code": "sah", "name": "саха тыла", "english": "Yakut", "path": "wikipedia_dicts/sah.csv"},
  {"code": "sat", "name": "ᱥᱟᱱᱛᱟᱲᱤ", "english": "Santali", "path": "wikipedia_dicts/sat.csv"},
  {"code": "sc", "name": "sardu", "english": "Sardinian", "path": "wikipedia_dicts/sc.csv"},
  {"code": "scn", "name": "sicilianu", "english": "Sicilian", "path": "wikipedia_dicts/scn.csv"},
  {"code": "sco", "name": "Scots", "english": "Scots", "path": "wikipedia_dicts/sco.csv"},
  {"code": "se", "name": "davvisámegiella", "english": "Northern Sami", "path": "wikipedia_dicts/se.csv"},
  {"code": "sg", "name": "Sängö", "english": "Sango", "path": "wikipedia_dicts/sg.csv"},
  {"code": "sgs", "name": "žemaitėška", "english": "Samogitian", "path": "wikipedia_dicts/bat-smg.csv"},
  {"code": "shi", "name": "Taclḥit", "english": "Tachelhit", "path": "wikipedia_dicts/shi.csv"},
  {"code": "sk", "name": "slovenčina", "english": "Slovak", "path": "wikipedia_dicts/sk.csv"},
  {"code": "sl", "name": "slovenščina", "english": "Slovenian", "path": "wikipedia_dicts/sl.csv"},
  {"code": "sm", "name": "Gagana Samoa", "english": "Samoan", "path": "wikipedia_dicts/sm.csv"},
  {"code": "smn", "name": "anarâškielâ", "english": "Inari Sami", "path": "wikipedia_dicts/smn.csv"},
  {"code": "sn", "name": "chiShona", "english": "Shona", "path": "wikipedia_dicts/sn.csv"},
  {"code": "so", "name": "Soomaaliga", "english": "Somali", "path": "wikipedia_dicts/so.csv"},
  {"code": "sq", "name": "shqip", "english": "Albanian", "path": "wikipedia_dicts/sq.csv"},
  {"code": "sr", "name": "српски", "english": "Serbian", "path": "wikipedia_dicts/sr.csv"},
  {"code": "srn", "name": "Sranantongo", "english": "Sranan Tongo", "path": "wikipedia_dicts/srn.csv"},
  {"code": "ss", "name": "SiSwati", "english": "Swati", "path": "wikipedia_dicts/ss.csv"},
  {"code": "st", "name": "Sesotho", "english": "Southern Sotho", "path": "wikipedia_dicts/st.csv"},
  {"code": "stq", "name": "Seeltersk", "english": "Saterland Frisian", "path": "wikipedia_dicts/stq.csv"},
  {"code": "su", "name": "Sunda", "english": "Sundanese", "path": "wikipedia_dicts/su.csv"},
  {"code": "sv", "name": "svenska", "english": "Swedish", "path": "wikipedia_dicts/sv.csv"},
  {"code": "sw", "name": "Kiswahili", "english": "Swahili", "path": "wikipedia_dicts/sw.csv"},
  {"code": "szl", "name": "ślůnski", "english": "Silesian", "path": "wikipedia_dicts/szl.csv"},
  {"code": "szy", "name": "Sakizaya", "english": "Sakizaya", "path": "wikipedia_dicts/szy.csv"},
  {"code": "tay", "name": "Tayal", "english": "Atayal", "path": "wikipedia_dicts/tay.csv"},
  {"code": "tcy", "name": "ತುಳು", "english": "Tulu", "path": "wikipedia_dicts/tcy.csv"},
  {"code": "tet", "name": "tetun", "english": "Tetum", "path": "wikipedia_dicts/tet.csv"},
  {"code": "tg", "name": "тоҷикӣ", "english": "Tajik", "path": "wikipedia_dicts/tg.csv"},
  {"code": "ti", "name": "ትግርኛ", "english": "Tigrinya", "path": "wikipedia_dicts/ti.csv"},
  {"code": "tk", "name": "Türkmençe", "english": "Turkmen", "path": "wikipedia_dicts/tk.csv"},
  {"code": "tl", "name": "Tagalog", "english": "Tagalog", "path": "wikipedia_dicts/tl.csv"},
  {"code": "tly", "name": "tolışi", "english": "Talysh", "path": "wikipedia_dicts/tly.csv"},
  {"code": "tn", "name": "Setswana", "english": "Tswana", "path": "wikipedia_dicts/tn.csv"},
  {"code": "to", "name": "lea faka-Tonga", "english": "Tongan", "path": "wikipedia_dicts/to.csv"},
  {"code": "tpi", "name": "Tok Pisin", "english": "Tok Pisin", "path": "wikipedia_dicts/tpi.csv"},
  {"code": "tr", "name": "Türkçe", "english": "Turkish", "path": "wikipedia_dicts/tr.csv"},
  {"code": "trv", "name": "Seediq", "english": "Taroko", "path": "wikipedia_dicts/trv.csv"},
  {"code": "ts", "name": "Xitsonga", "english": "Tsonga", "path": "wikipedia_dicts/ts.csv"},
  {"code": "tt", "name": "татарча", "english": "Tatar", "path": "wikipedia_dicts/tt.csv"},
  {"code": "tum", "name": "chiTumbuka", "english": "Tumbuka", "path": "wikipedia_dicts/tum.csv"},
  {"code": "tw", "name": "Twi", "english": "Twi", "path": "wikipedia_dicts/tw.csv"},
  {"code": "ty", "name": "reo tahiti", "english": "Tahitian", "path": "wikipedia_dicts/ty.csv"},
  {"code": "udm", "name": "удмурт", "english": "Udmurt", "path": "wikipedia_dicts/udm.csv"},
  {"code": "uk", "name": "українська", "english": "Ukrainian", "path": "wikipedia_dicts/uk.csv"},
  {"code": "uz", "name": "oʻzbekcha", "english": "Uzbek", "path": "wikipedia_dicts/uz.csv"},
  {"code": "ve", "name": "Tshivenda", "english": "Venda", "path": "wikipedia_dicts/ve.csv"},
  {"code": "vec", "name": "vèneto", "english": "Venetian", "path": "wikipedia_dicts/vec.csv"},
  {"code": "vep", "name": "vepsän kel’", "english": "Veps", "path": "wikipedia_dicts/vep.csv"},
  {"code": "vi", "name": "Tiếng Việt", "english": "Vietnamese", "path": "wikipedia_dicts/vi.csv"},
  {"code": "vls", "name": "West-Vlams", "english": "West Flemish", "path": "wikipedia_dicts/vls.csv"},
  {"code": "vo", "name": "Volapük", "english": "Volapük", "path": "wikipedia_dicts/vo.csv"},
  {"code": "vro", "name": "võro", "english": "Võro", "path": "wikipedia_dicts/fiu-vro.csv"},
  {"code": "wa", "name": "walon", "english": "Walloon", "path": "wikipedia_dicts/wa.csv"},
  {"code": "war", "name": "Winaray", "english": "Waray", "path": "wikipedia_dicts/war.csv"},
  {"code": "wo", "name": "Wolof", "english": "Wolof", "path": "wikipedia_dicts/wo.csv"},
  {"code": "xal", "name": "хальмг", "english": "Kalmyk", "path": "wikipedia_dicts/xal.csv"},
  {"code": "xh", "name": "isiXhosa", "english": "Xhosa", "path": "wikipedia_dicts/xh.csv"},
  {"code": "xmf", "name": "მარგალური", "english": "Mingrelian", "path": "wikipedia_dicts/xmf.csv"},
  {"code": "yo", "name": "Yorùbá", "english": "Yoruba", "path": "wikipedia_dicts/yo.csv"},
  {"code": "za", "name": "Vahcuengh", "english": "Zhuang", "path": "wikipedia_dicts/za.csv"},
  {"code": "zea", "name": "Zeêuws", "english": "Zeelandic", "path": "wikipedia_dicts/zea.csv"},
  {"code": "zu", "name": "isiZulu", "english": "Zulu", "path": "wikipedia_dicts/zu.csv"}
];
